if(NOT DEFINED MYSQL_PORT)
    message(FATAL_ERROR "MySQL port was not defined (-DMYSQL_PORT)")
elseif(NOT DEFINED MYSQL_XAPI_PORT)
    message(FATAL_ERROR "MySQL XAPI port was not defined (-DMYSQL_XAPI_PORT)")
elseif(NOT DEFINED MYSQL_PID_PATH)
    message(FATAL_ERROR "MySQL PID path was not defined (-DMYSQL_PID_PATH)")
elseif(NOT DEFINED MYSQL_DATA_DIR)
    message(FATAL_ERROR "MySQL data directory was not defined (-DMYSQL_DATA_DIR)")
elseif(NOT DEFINED MYSQL_ERRORLOG_PATH)
    message(FATAL_ERROR "MySQL error.log path was not defined (-DMYSQL_ERRORLOG_PATH)")
elseif(NOT DEFINED MYSQL_SOCKET_PATH)
    message(FATAL_ERROR "Mosquitto unix socket path was not defined (-DMYSQL_SOCKET_PATH)")
endif()

if(NOT DEFINED IN_FILE_PATH OR NOT DEFINED OUT_FILE_PATH)
    message(FATAL_ERROR "Input/output file paths must be specified (-DIN_FILE_PATH) (-DOUT_FILE_PATH)")
endif()

configure_file("${IN_FILE_PATH}" "${OUT_FILE_PATH}")
message("${IN_FILE_PATH} -> ${OUT_FILE_PATH}")