list(APPEND CMAKE_FIND_LIBRARY_PREFIXES "" "lib")
list(APPEND CMAKE_PREFIX_PATH "/usr/lib/x86_64-linux-gnu")

find_library(MOSQUITTO_DYNSEC_LIB_PATH NAMES mosquitto_dynamic_security)
find_program(MOSQUITTO_EXE_PATH        NAMES mosquitto)
find_program(MOSQUITTO_CTRL_EXE_PATH   NAMES mosquitto_ctrl)
find_program(OPENSSL_EXE_PATH          NAMES openssl)

if(NOT DEFINED MOSQUITTO_RUNTIME_DIR)
    message(FATAL_ERROR "Mosquitto runtime directory wasn't specified (-DMOSQUITTO_RUNTIME_DIR)")
endif()

if(NOT DEFINED MOSQUITTO_SECRETS_DIR)
    set(MOSQUITTO_SECRETS_DIR "${MOSQUITTO_RUNTIME_DIR}/secrets")
endif()

set(MOSQUITTO_PKEY_PATH  "${MOSQUITTO_SECRETS_DIR}/pkey.pem")
set(MOSQUITTO_CERT_PATH "${MOSQUITTO_SECRETS_DIR}/cert.pem")

set(MOSQUITTO_PID_PATH "${MOSQUITTO_RUNTIME_DIR}/mosquitto.pid")
set(MOSQUITTO_CONF_PATH "${MOSQUITTO_RUNTIME_DIR}/mosquitto.conf")
set(MOSQUITTO_DYNSEC_CONF_PATH "${MOSQUITTO_RUNTIME_DIR}/dynsec.json")
set(MOSQUITTO_PERSISTENCE_DIR "${MOSQUITTO_RUNTIME_DIR}")

if(NOT MOSQUITTO_EXE_PATH)
    message(FATAL_ERROR "Could not find path to program `mosquitto` (-DMOSQUITTO_EXE_PATH)")
elseif(NOT MOSQUITTO_CTRL_EXE_PATH)
    message(FATAL_ERROR "Could not find path to program `mosquitto_ctrl` (-DMOSQUITTO_CTRL_PATH)")
elseif(NOT MOSQUITTO_DYNSEC_LIB_PATH)
    message(FATAL_ERROR "Could not find path to shared library `mosquitto_dynamic_security` (-DMOSQUITTO_DYNSEC_LIB_PATH)")
elseif(NOT OPENSSL_EXE_PATH)
    message(FATAL_ERROR "Couldn't find program `openssl` (-DOPENSSL_EXE_PATH)")
elseif(NOT DEFINED MOSQUITTO_PORT)
    message(FATAL_ERROR "Mosquitto port not specified (-DMOSQUITTO_PORT)")
endif()

message("MOSQUITTO_RUNTIME_DIR:      ${MOSQUITTO_RUNTIME_DIR}")
message("MOSQUITTO_PORT:             ${MOSQUITTO_PORT}")
message("MOSQUITTO_CONF_PATH:        ${MOSQUITTO_CONF_PATH}")
message("MOSQUITTO_DYNSEC_CONF_PATH: ${MOSQUITTO_DYNSEC_CONF_PATH}")
message("MOSQUITTO_EXE_PATH:         ${MOSQUITTO_EXE_PATH}")
message("MOSQUITTO_CTRL_EXE_PATH:    ${MOSQUITTO_CTRL_EXE_PATH}")
message("MOSQUITTO_DYNSEC_LIB_PATH:  ${MOSQUITTO_DYNSEC_LIB_PATH}")
message("OPENSSL_EXE_PATH:           ${OPENSSL_EXE_PATH}")
message("MOSQUITTO_CERT_PATH:        ${MOSQUITTO_CERT_PATH}")
message("MOSQUITTO_PKEY_PATH:        ${MOSQUITTO_PKEY_PATH}")

configure_file("${CMAKE_CURRENT_LIST_DIR}/.env.in"
               "${CMAKE_CURRENT_LIST_DIR}/.env.local" @ONLY)
message("-----> ${CMAKE_CURRENT_LIST_DIR}/.env.local")