cmake_minimum_required(VERSION 3.16)
project(gecko LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
enable_testing()

if(WIN32)
    set(_shell_command cmd /c)
    set(_script_ext bat)
    set(_static_lib_ext lib)
    set(_shared_lib_ext dll)
    set(_executable_dot_ext .exe)
else()
    set(_shell_command bash -c)
    set(_script_ext sh)
    set(_static_lib_ext a)
    set(_shared_lib_ext so)
    set(_executable_dot_ext "")
endif()

add_subdirectory(shared)
add_subdirectory(api)